### ISSUE TITLE
Delete the field 'Activity Details' 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/ServicesAdvisor-2.0#1]

**Comment by fmann** [comment]
The activity details are displayed the SA front end. 

I believe the idea here is to remove activity details as its own field and make it a part of the Sector > Sub-Sector selection as mentioned in ticket #2

**Comment by PeaceGeeks** [comment]
That is correct. It sounds like you want to wait to remove this field till we can figure out what to do with historic records, but actually it just occurred to me that none of the existing data is production data - these are all test records, so there will be no need to reconcile this information.

**Comment by fmann** [comment]
We are keeping Activity Details but chaining it with Sector and Category.
