### ISSUE TITLE
Sector > Sub-Sector > Activity needs to be dynamic to handle new entries

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/ServicesAdvisor-2.0#12]

**Comment by fmann** [comment]
I think this a reference to the fact that if you add a new Sector or don't set a Sector, the SA client code crashes with an error about not being able to find an icon for it.

Ideally the SA client code would have a default icon it would use if it came across an unknown sector.

**Comment by PeaceGeeks** [comment]
Yes that is correct - Floyd, would it be ok if I brought Luke and Tucker
into this repo/ question or should we wait till we meet with them? And
given the urgency (because really they can't launch the new version without
this), should we set up that meeting for early next week?




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype.* reneeontheroad

**Comment by fmann** [comment]
If it is going to be managed by a different group of developers, I think we should probably keep SA front end tickets on that project rather than this one. But we certainly will need to coordinate changes between the two systems.

**Comment by fmann** [comment]
Sectors are now pulled from the Drupal backend.
