### ISSUE TITLE
User cannot login with registered email but can with username - any idea why? 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/ServicesAdvisor-2.0#14]

**Comment by fmann** [comment]
Email login is not core functionality.  Contrib email_registration module now installed and enabled.

**Comment by PeaceGeeks** [comment]
Hi Floyd

Two points:

1. Can you clarify that you have implemented this contrib module and other,
what you have done to resolve this ticket.
2. If you have installed Zen Hub, and if this ticket is completed, can you
instead select the 'Done' Pipeline instead of closing the ticket. As Magdi
pointed out in a previous communication, our process is for our team to QA
tickets in the 'Done' pipeline, not for devs to QA and close them.







*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype.* reneeontheroad

**Comment by fmann** [comment]
1. Contrib email_registration module now installed and enabled.

2. Could you add a done tag that I could use so I don't have to install Zen Hub? I work on a lot of GitHub projects for a lot of clients and am not enthusiastic about creating a new dependency / process flow for just one project.

**Comment by PeaceGeeks** [comment]
Installing ZenHub doesn't prevent you from using GitHub in the normal way
with a list of tickets. All of out projects are managed this way (I just
have not been enforcing these processes while we have been trying to get
through this work). I understand your reluctance, but please understand
that what you are asking us to do instead is to modify our organizational
processes for one person. It won't interfere with using GitHub normally, it
will just allow you to view Pipelines for projects where that applied. Its
quite useful.






*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype.* reneeontheroad
