### ISSUE TITLE
Finalize documentation for Services Advisor 2.0

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/ServicesAdvisor-2.0#20]

**Comment by PeaceGeeksProjects** [comment]
Updated Site Admin and Group Admin sections.
Waiting for decision on Group Member capability.

**Comment by PeaceGeeksProjects** [comment]
Review doc at: https://docs.google.com/document/d/1AnE5PL5UoIquAKXg8VGVolONJsc_o-ZmoAuInPlxFuo/edit#heading=h.ablvw3ka375o

**Comment by PeaceGeeksProjects** [comment]
https://drive.google.com/open?id=1AnE5PL5UoIquAKXg8VGVolONJsc_o-ZmoAuInPlxFuo
