### ISSUE TITLE
Clarify questions on adding users

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/ServicesAdvisor-2.0#21]
How should users get added? 
Are approvals required? 
If so, by whom?

**Comment by PeaceGeeksProjects** [comment]
The proposed structure for users is as follows:
Site Administrator
Group Administrator
Group Member

Site Administrator:  Manages Users (Group Admins & Members) and Partners (Groups) and assigns Group Admins to their group.
Group Administrator: Manages their own Group, its Service Locations and Members (from existing users).
Group Members: Manages Service Locations for their group.

**Comment by PeaceGeeksProjects** [comment]
The workflow would be as follows:
New Org:

    Apply (don't know the current process but we could create an application form on the site)
    Approval (???)
        Org Rejected (???)
        Org Accepted:
            Site Administrator creates the Org, OrgAdmin, & OrgMember and communicates their credentials.
            Site Administrator gives Org Administration role to OrgAdmin.
    Initiation:
        OrgAdmin fills in the Org info & Logo
        OrgAdmin adds OrgMember to the Org
        OrgAdmin & OrgMember create all their Service Locations


Existing Org:

    OrgAdmin maintains Org info & Logo
    OrgAdmin & OrgMember maintain all their Service Locations

**Comment by PeaceGeeksProjects** [comment]
New agreed upon workflow:
New Org - Site Administrator 
1. requests 2 emails for OrgAdmin & OrgMember 
2. creates the Org, OrgAdmin, & OrgMember and communicates their credentials to the Orfg
3. gives Org Administration role to OrgAdmin.

Existing Org:
OrgAdmin maintains Org info & Logo
OrgAdmin & OrgMember maintain all their Service Locations

Closing this issue
