### ISSUE TITLE
Add 'Other' text field to Intake Criteria 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/ServicesAdvisor-2.0#24]
This is pending confirmation of Intake criteria list.

**Comment by PeaceGeeksProjects** [comment]
@mackh   Other is there but refers to a non-existant Comments
![24](https://cloud.githubusercontent.com/assets/16202351/17599493/3459df6e-5fb4-11e6-8735-16cd1358d671.jpg)

**Comment by PeaceGeeksProjects** [comment]
see https://github.com/PeaceGeeksSociety/servicesadvisor-3.0/issues/35
