### ISSUE TITLE
Cleanup unused Taxonomy Vocabularies

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/ServicesAdvisor-2.0#27]
Delete all vocabularies that do not start with Service... e.g. forums, Tags

**Comment by jinng2016** [comment]
Created pull request #50

**Comment by PeaceGeeksProjects** [comment]
Verfied on http://dev.unhcrjordan.peacegeeks.org/

**Comment by PeaceGeeksProjects** [comment]
Please remove the old Sector, Category, Activities Taxonomies (Replaced by the Nested Categories)

**Comment by jinng2016** [comment]
Submitted merge request #60

**Comment by PeaceGeeksProjects** [comment]
verified
