### ISSUE TITLE
Allow Org Admins to edit the Organizational Overview field

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/ServicesAdvisor-2.0#28]
![28](https://cloud.githubusercontent.com/assets/16202351/15581597/d5cb99ca-2321-11e6-8cf9-f26cf7f19158.jpg)

**Comment by mackh** [comment]
This is still an issue, and should be fixed

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev
