### ISSUE TITLE
Add a text field to 'Office Information'

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/ServicesAdvisor-2.0#29]
Right now there is no way to add additional details to office information. We want to add a new text field called 'Additional Details' at the bottom of the 'Office Information' box that can allow users to add a small additional text information blurb. 
(Eg. If the hours are twice a month, they can specify when etc)

<img width="562" alt="screen shot 2016-05-26 at 4 40 18 pm" src="https://cloud.githubusercontent.com/assets/1025545/15593424/d73c9112-2360-11e6-8fb5-05f47d1fc855.png">

**Comment by jinng2016** [comment]
Pushed the backend of text location to branch 'feature/29-add-text-to-office-location'. Needs FE work on it

**Comment by fmann** [comment]
Ticket for FE change is #30

**Comment by PeaceGeeksProjects** [comment]
Verified on http://dev.unhcrjordan.peacegeeks.org/
