### ISSUE TITLE
Change how Node Title is set

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/ServicesAdvisor-2.0#3]
Remove the free form title field ‘Site/ Location’ 
Enforce a node title using the service type plus location as the node title, as per Services Advisor 1.0. (e.g. MAFRAQ GOVERNORATE: HEALTH SERVICES)

**Comment by fmann** [comment]
Auto Node Title is installed now. I also added a hook_node_presave call to handle the localization.
