### ISSUE TITLE
Rename, add 4th administrative level for locations in General Information

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/ServicesAdvisor-2.0#31]
Currently we have 3 categories, but we want to rename them, and add a fourth level.

<img width="550" alt="screen shot 2016-05-26 at 4 51 19 pm" src="https://cloud.githubusercontent.com/assets/1025545/15593528/17dc017a-2362-11e6-9d3d-995581691cb5.png">

This will be changed to:
Level 1 -> Sector (Single Select)
Level 2 -> Sub-Sector (Single Select)
Level 3 -> Activity (Single Select)
Level 4 ->  Category (Multi Select)

**Comment by PeaceGeeks** [comment]
Renee is meeting with UNHCR on May 31 to discuss this ticket

**Comment by mackh** [comment]
completed to client satisfaction

**Comment by PeaceGeeksProjects** [comment]
Closing then
