### ISSUE TITLE
Prefer GPS coordinates when displaying entries on the map

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/ServicesAdvisor-2.0#34]
We should try to use accurate GPS coordinates when available.

**Comment by fmann** [comment]
When both a location selected from the drop downs and raw GPS coordinates are provided, the GPS coordinates are used on the map. So I believe there is nothing to be done for this ticket.

**Comment by PeaceGeeksProjects** [comment]
No Action needed
