### ISSUE TITLE
Rename user roles and Adjust permissions

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/ServicesAdvisor-2.0#36]
Rename Drupoal User
Amani Admin => Site Admin (collect feedback, manage all site users, add service partners, add service locations, manage taxonomies)

Adjust Permisions for Organic Groups
- OrgAdmin (manage service locations, manage organizational users, print service sheets as per new features) 
- OrgMember (manage service locations, print service sheets as per new features)

**Comment by PeaceGeeksProjects** [comment]
Roles are defined in #21

**Comment by PeaceGeeksProjects** [comment]
Verified
