### ISSUE TITLE
Create new dashboard for Service Providers to see other providers

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/ServicesAdvisor-2.0#40]
We want to create a private directory (dashboard) of more detailed info for service providers making referrals. Service providers should be able to see all other providers, and more details than the public client. This will allow making referrals easier.

**Comment by PeaceGeeksProjects** [comment]
Show expiry dates on the list and allow sorting

**Comment by jinng2016** [comment]
Sorting is on [ticket 42](https://github.com/PeaceGeeksSociety/ServicesAdvisor-2.0/issues/42).

**Comment by PeaceGeeksProjects** [comment]
@fmann Please Change 'All Organizations' to 'All Services' in the menu and the page title.
