### ISSUE TITLE
New User Interface

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/ServicesAdvisor-2.0#41]
The following mocks have not been vetted.

[Service Desk For Providers.pdf](https://github.com/PeaceGeeksSociety/ServicesAdvisor-2.0/files/285562/Service.Desk.For.Providers.pdf)

It would be good to work with a designer based on the new requirements and have more finished mocks. We need to call out any inconsistencies in the current mocks.

**Comment by PeaceGeeksProjects** [comment]
New design now in place
