### ISSUE TITLE
Add new filters for generating lists

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/ServicesAdvisor-2.0#42]
In the org dashboard we need more ways to filter

- Organization
- Sector > Category > Activity Details
- Service Location

**Comment by jinng2016** [comment]
#51 has placeholders for filters but still requires work

**Comment by jinng2016** [comment]
Created most of the filters. Following tasks still need to be done:
* Service Organization Filter
* Layout of list item

**Comment by PeaceGeeksProjects** [comment]
Filters are now in place
