### ISSUE TITLE
Abbreviated Partner Name should be unique

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/ServicesAdvisor-2.0#46]
Requested by Murad

**Comment by mackh** [comment]
On the Service Partner, force the node title to be unique

http://admin.jordan.servicesadvisor.org/admin/structure/types/manage/service_partner/fields

https://www.drupal.org/project/unique_node_title - maybe this will work?

**Comment by jinng2016** [comment]
Submitted #48. Used module 'Unique Field' instead of 'Unique Title'

**Comment by mackh** [comment]
great, thanks, will review

**Comment by PeaceGeeksProjects** [comment]
Verified on http://dev.unhcrjordan.peacegeeks.org/
