### ISSUE TITLE
Remove 'Edit My Organization' and 'Manage Team' from the menu and capability for Org Members

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/ServicesAdvisor-2.0#59]
Only Org Admins can 'Edit' their Orgs.

**Comment by fmann** [comment]
Not true. At the moment all Org Members can edit the group membership and the Organization node.

**Comment by PeaceGeeksProjects** [comment]
@fmann That is a requirement from the usage workflow perspective, Not a statement :)

**Comment by jinng2016** [comment]
With #77 and #78 , is this ticket still relevant?

**Comment by PeaceGeeksProjects** [comment]
not relevant anymore
