### ISSUE TITLE
Cleanup duplicate Service Partners

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/ServicesAdvisor-2.0#64]
@PeaceGeeks There are quite a few Duplicate Groups as shown here
http://admin.jordan.servicesadvisor.org/admin/content?sort=asc&order=Title

These NEED to be cleaned up now that No Duplicate 'Title' is allowed.

May be the Locations can be moved from one to the other then delete the empty group.

**Comment by mackh** [comment]
this is complete

**Comment by PeaceGeeksProjects** [comment]
Closing then...
