### ISSUE TITLE
Cleanup Group Admins

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/ServicesAdvisor-2.0#65]
Currently there are quite a few groups 'owned' by Superadmin, Admin, & Murad.  These need to be cleaned up to be owned by the proper Group Administrator.

**Comment by mackh** [comment]
will not fix, Jordan UNHCR will be responsible for user and group admin tasks

**Comment by PeaceGeeksProjects** [comment]
Yes this is assigned to the UNHCR team

**Comment by PeaceGeeksProjects** [comment]
Verified.  All groups are 'owned' by 'Admin'.
