### ISSUE TITLE
Changing the text on the User Landing Page button to “Add New Service” only

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/ServicesAdvisor-2.0#69]
![69](https://cloud.githubusercontent.com/assets/16202351/16427678/3e792526-3d23-11e6-8990-36549f29f0e6.jpg)

**Comment by mackh** [comment]
Anywhere "Service Location" appears we would want to rename it to "Service" this would include views headers, and anywhere its translated into Arabic, we'll need to figure out what the translation is for Service

**Comment by robwild** [comment]
I have 63 matches on code for 'Service Location', but some of these I think are related to back end functions, do you want all of these changing?

**Comment by mackh** [comment]
No user viewable labels only please

**Comment by PeaceGeeksProjects** [comment]
solved by new design
