### ISSUE TITLE
Change 'Edit Account'to 'Account' on Menu

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/ServicesAdvisor-2.0#78]
![77](https://cloud.githubusercontent.com/assets/16202351/16428633/93bbb914-3d27-11e6-94e5-be95d9d06fc6.jpg)
![78](https://cloud.githubusercontent.com/assets/16202351/16428993/642ac85a-3d29-11e6-9960-7d3596150999.jpg)

**Comment by jinng2016** [comment]
See #82
