### ISSUE TITLE
Change service partner to Organization in the system in general

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/ServicesAdvisor-2.0#79]

**Comment by jinng2016** [comment]
I'm presuming this means renaming content-type 'Service Partner' and all related stuff to 'Service Organization'

**Comment by PeaceGeeksProjects** [comment]
@jinng2016 renaming content-type 'Service Partner' and all related stuff to just 'Organazatrion'

**Comment by PeaceGeeksProjects** [comment]
Done
