### ISSUE TITLE
Service Location Titles - Add source NID to autogenerated title

### ISSUE THREAD

**Issue by mackh** [PeaceGeeksSociety/ServicesAdvisor-2.0#88]
Client would like a way to differentiate records from each other, for many providers, the titles are duplicated because they are in the same location, and category.

Add the NID of the source node to the title, so the new title pattern will be

Location Leaf : Ist selected Category : Source NID - Awjan al Gharbi: Protection : 1019

Note that the title needs to be consistent in all languages, so the NID needs to be the source node, not the translated node.

Regen all node labels on dev, then reassign to me for testing pls

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev
