### ISSUE TITLE
Rename Office Information section

### ISSUE THREAD

**Issue by mackh** [PeaceGeeksSociety/ServicesAdvisor-2.0#89]
On the Services Location content type, please rename 

The field set from "Office Information" to "Availability"

Rename "Office Hours" field to "Hours"

**Comment by arvandtiv** [comment]
https://github.com/PeaceGeeksSociety/ServicesAdvisor-2.0/commit/5ad00af4a677c76a9322c1967b99e0f5f9f40b43

**Comment by PeaceGeeksProjects** [comment]
@arvandtiv Hours still show as Office Hours...
see http://dev.unhcrjordan.peacegeeks.org/node/318/edit

**Comment by smithmilner** [comment]
Done and applied to the 3.0 repository https://github.com/PeaceGeeksSociety/servicesadvisor-3.0/commit/9a4c4cafd6bcc3c43d3968fa1d9ad7b6e1e35043

**Comment by PeaceGeeksProjects** [comment]
Verified
