### ISSUE TITLE
Logos are hardcoded into the frontend - paths to logos should load with feed

### ISSUE THREAD

**Issue by mackh** [PeaceGeeksSociety/ServicesAdvisor-2.0#90]
Currently service providers upload logos to the backend with their org profile, but on the frontend , the logos are hardcoded in the angular app.  This is a left over from prototyping. 

Create a method to update the SA frontend logos with the uploaded logos from the backend

Assigning to both Floyd and Smith to try to find the best solution.  If this is very difficult, let me know and we'll update the hardcoded set as a half measure.

**Comment by smithmilner** [comment]
Adding logo urls to json feed in servicesadvisor-3.0 https://github.com/PeaceGeeksSociety/servicesadvisor-3.0/commit/cb3f7ce645f01959e5d2fd745326a5430c3b6789

We need to take care that the changes happen in the Angular app after this has been deployed.

**Comment by smithmilner** [comment]
I have completed the changes to the Angular app now as well. They are available in the "feature/feed_logos" branch. This should get deployed as soon as the logos are available in the json feed.

**Comment by smithmilner** [comment]
Done and Deployed.
