### ISSUE TITLE
Allow map to filter by top level on click

### ISSUE THREAD

**Issue by mackh** [PeaceGeeksSociety/ServicesAdvisor-2.0#91]
When using the frontend map, clicking the top level category should filter results and show the sub category options

https://www.evernote.com/l/AAhYwr2PMM9KxLWDoEXgMRfI4CH__Kp9X40

This is a high priority for the client

I have assigned all of you, not sure who knows the solution here, work it out

**Comment by smithmilner** [comment]
Done and Deployed.
