### ISSUE TITLE
CSV Export - break category into multiple cols

### ISSUE THREAD

**Issue by mackh** [PeaceGeeksSociety/ServicesAdvisor-2.0#93]
CSV FIle - would like the field per taxonomy level, so they can filter it
Would be split on commas - Health, Primary Care, Non communicable diseases, Mental health care, Secondary & Tertiary Care, Non communicable diseases, Outpatient psychiatric care

So each level of the main category taxo would be in its own col in the the CSV

**Comment by smithmilner** [comment]
Drupal taxonomies don't really have any depth functionality. This as described, isn't really possible without custom views work and custom taxonomy database columns. What I can do though is add another column which shows the "root term" being used.

Another issue here is that each service location can select multiple service categories. This means that we will see the service location duplicated in the list with the only field thing changed being the "root term" field.

Is this solution appropriate?

**Comment by mackh** [comment]
Good point, we should validate what the client wants here, they would like to use the spreadsheet for reporting and analysis.  If there are duplicated records in the sheet, that will make it hard to count them, I will follow up with the client

**Comment by PeaceGeeksProjects** [comment]
May be add the node ID for each line si it is 'obvious' where it is duplicated and could be 'grouped' for reporting accurately?

**Comment by mackh** [comment]
Client says "Very important since all of the reporting/analysis of the records will be done based on that. I understand your point and multi-records/one location and vice versa is OK since it will be different record. Same applies for locations (we also need to report on services per location for the whole country)"

so I think we should repeat the line for every different value in the service type, and make sure the locations taxonomy is similarly divided

**Comment by PeaceGeeksProjects** [comment]
Verified on Jordan
